sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t oyeme/docker-react -f Dockerfile.dev . 

script:
  - docker run oyeme/docker-react npm run test -- --coverage


