os: linux
language: shell

services: 
  - docker

before_install:
  - docker build -t oyeme/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true  oyeme/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region:  "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-241284018316"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

